---
- name: Gandalf server (mongodb/gandalf/archive-server/git-daemon)
  user: root
  hosts: tsuru
  vars_files:
  - "./group_vars/users.yml"
  roles:
  - name: ubuntu
    repository: "http://ubuntu.c3sl.ufpr.br/ubuntu/"
    components:
    - main
    - restricted
    - universe
    - multiverse
    channels:
    - updates
    install:
    - vim
    - sudo
    - htop
    - mongodb
    - redis-server
    - docker.io
    - docker-registry

  - name: "users"
    make:
    - "{{ users.build }}"
    - "{{ users.gandalf }}"

  - name: "gandalf"
    builder: "{{ users.build }}"
    runner: "{{ users.gandalf }}"
    data_dir: /srv/repo

  - name: "git-daemon"
    runner: "{{ users.gandalf }}"
    data_dir: /srv/repo

  - name: "archive-server"
    builder: "{{ users.build }}"
    runner: "{{ users.gandalf }}"
    data_dir: /srv/repo

  - name: "tsuru"
    builder: "{{ users.build }}"
    runner: "{{ users.gandalf }}"
    git_template_dir: "/tmp/"

  - name: "planb"
    builder: "{{ users.build }}"
    runner: "{{ users.gandalf }}"

  - name: "tsuru-client"
    builder: "{{ users.build }}"

  tasks:
  - name: Docker tweak
    lineinfile:
      dest: /lib/systemd/system/docker.service
      regexp: ^ExecStart=
      line: ExecStart=/usr/bin/dockerd -H fd:// tcp://0.0.0.0:2376








