---
- name: Install deps
  apt:
    name: "{{ deps }}"

- name: Get sources@{{ version }}
  become: yes
  become_user: "{{ builder.name }}"
  git:
    repo: "{{ repo }}"
    dest: "{{ builder.home }}/src/github.com/tsuru/tsuru"
    version: "{{ version }}"

- name: Build binaries
  become: yes
  become_user: "{{ builder.name }}"
  shell: "GOPATH={{ builder.home }} make binaries"
  args:
    chdir: "{{ builder.home }}/src/github.com/tsuru/tsuru"
    creates: "build"

- name: Install binaries
  copy:
    remote_src: yes
    src: "{{ builder.home }}/src/github.com/tsuru/tsuru/build/tsurud"
    dest: "/usr/bin/tsurud"
    mode: "0755"

- name: Check /etc/tsuru dir
  file:
    name: /etc/tsuru
    state: directory

- name: Install config
  template:
    src: "./templates/tsuru.conf.j2"
    dest: "/etc/tsuru/tsuru.conf"

- name: Install systemd service
  template:
    src: "./templates/tsurud.service.j2"
    dest: "/etc/systemd/system/tsurud.service"

- name: Enable systemd service
  service:
    name: tsurud
    enabled: yes
    state: started

- name: Token to Gandalf
  shell: |
    tsurud token | awk \
    '{print "export TSURU_HOST={{ tsuru_uri }}\nexport TSURU_TOKEN="$0}' \
    > "{{ git_template_dir }}/.bash_profile" \
    && > /etc/gandalf_secret
  args:
    creates: "/etc/gandalf_secret"



