---
- name: Install git
  apt:
    name: git
    
- name: Create work dir
  file:
    name: "{{ data_dir }}"
    state: directory
    recurse: yes
    owner: "{{ runner.name }}"
    group: "{{ runner.group }}"

- name: Install service
  template:
    src: ./templates/git-daemon.service.j2
    dest: /etc/systemd/system/git-daemon.service

- name: Enable and start service
  service:
    name: git-daemon
    enabled: yes
    state: started
